### ISSUE TITLE
How to pass the module name?

### ISSUE THREAD

**Issue by Klaster1** [PillowPillow/ng-annotations#1]
There seems to be an argument where you can pass the module name, but documentation doesn't say anything about it.

**Comment by PillowPillow** [comment]
Hi, there is two methods to declare a component to a module.

``` javascript
//sample files:

/*file1.js*/
import {service} from 'node_modules/ng-annotations';

@service()
export default class MyService {}


/*file2.js*/
import {controller, inject} from 'node_modules/ng-annotations';
import {$name as myService} from './file1';

@controller()
@inject(myService)
export default class MyController {}
```

> 1) using the autodeclare method provided by the annotated class:  
> you can pass a module instance or the module name

``` javascript
import myService from './file1';
import myController from './file2';

var app = angular.module('app', []);
export app.name; 

[myService, myController].forEach(component => component.autodeclare(app));
```

``` javascript
//or directly in the class file
import {service} from 'node_modules/ng-annotations';

@service()
class MyService {}

MyService.autodeclare('moduleName');
```

> 2) using the $name and $component properties

``` javascript
import myService from './file1';
import myController from './file2';

var app = angular.module('app', []);
export app.name; // useful if you wanna use the import system with the module dependency injection system.

app.service(myService.$name, myService.$component);
app.controller(myController.$name, myController.$component);
```

NB: you have two full examples in the /example folder

**Comment by Klaster1** [comment]
Thanks, that'll do the job, but both options look pretty clunky to me. Have you thought about optional argument to specify the module name?

**Comment by PillowPillow** [comment]
I wanted to create an optional parameter or another annotation but there is some problems.

first proposal: the optional parameter  

> syntax

``` javascript
import {controller} from 'ng-annotations';

// we can't consider to add a second parameter because the component name is already optional
@controller({name: 'MyCtrl', module: 'MyModule'})
class MyController {}
```

second proposal: the annotation  

``` javascript
import {controller, autodeclare} from 'ng-annotations';

@controller('MyCtrl')
@autodeclare('MyModule')
class MyController {}
```

both solutions had the same problem, i don't know when trigger the module declaration.
Let me explain: you can add more than one decorator to your class (@inject for example), so the component annotation will be triggered according to the order of the annotations but the module declaration must occur AFTER the execution of all the decorators.

Example:

> with the first proposal:

``` javascript
import {controller, inject} from 'ng-annotations';

@controller({name: 'MyCtrl', module: 'MyModule'})
@inject('someService')
class MyController {}
```

> in this case it will be ok because @inject will be triggered before @controller

``` javascript
import {controller, inject} from 'ng-annotations';

@inject('someService')
@controller({name: 'MyCtrl', module: 'MyModule'})
class MyController {}
```

> but in this case it will fail because @inject will be triggered after @controller.
> the module declaration will take place before the filling of the $inject array, it will prevent the dependency injection.
> same thing with the second proposal

If you have an idea to fix this, I will be happy to implement it.
