### ISSUE TITLE
What about stateful filters?

### ISSUE THREAD

**Issue by TheDadi** [PillowPillow/ng-annotations#2]

**Comment by PillowPillow** [comment]
Hi, thank's for your issue.
At this time the stateful filters can't be created by ng-annotations.

I will fix it today.

**Comment by PillowPillow** [comment]
the last version fixed it.
You simply have to define a `$stateful` property to true.

``` javascript
import {filter, inject} from 'ng-annotations';

@filter()
@inject('dependency')
class MyFilter {
    $stateful=true;
    $filter(param) { return param; }
}
```

The documentation is up-to-date.
