### ISSUE TITLE
Use Typescript 

### ISSUE THREAD

**Issue by luisvt** [PillowPillow/ng-annotations#8]
It would be cool if this library gets converted to typescript

**Comment by PillowPillow** [comment]
Hello luisvt, 
I never try to use the library with typescript but it shouldn't need a full rewrite to typescript in order to make it compatible.
I'm a bit busy right now but i'll check it in the next few days

**Comment by luisvt** [comment]
I have done already the Typescript migration, however the annotations `@attach` and `@conceal` doesn't work. This is because Typescript doesn't support getting descriptor from attributes, it only supports getting it from methods

**Comment by PillowPillow** [comment]
mmmh, i m pretty sure typescript allows usage of descriptor on attributes. I'm using this in an other library [ng2-webstorage](https://github.com/PillowPillow/ng2-webstorage). Moreover, angular2 uses this with its single injection.

**Comment by luisvt** [comment]
This is my branch, https://github.com/luisvt/ng-annotations/tree/convert-js-to-ts?files=1

Maybe I'm doing something wrong in Ts configuration please let me know if you find something

**Comment by luisvt** [comment]
I think next link describes why typescript doesn't support `Property Descriptors` on attributes:

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Decorators.md#property-decorators

the most important part is this:

> NOTE  A Property Descriptor is not provided as an argument to a property decorator due to how property decorators are initialized in TypeScript. This is because there is currently no mechanism to describe an instance property when defining members of a prototype, and no way to observe or modify the initializer for a property. As such, a property decorator can only be used to observe that a property of a specific name has been declared for a class.

this is the error when I try to run the tests:

```
Uncaught TypeError: Cannot set property 'configurable' of undefined
```

**Comment by PillowPillow** [comment]
I think we can do a workaround by overriding the property if there is no descriptor provided by typescript.

Consider something like this

``` typescript
export function Annotation() {
    return (targetedClass:Object, name:string, descriptor:any) => {

        if(!descriptor)
            Object.defineProperty(targetedClass, name, {
                value: null,
                configurable: true
            });

        ...

    };
}
```

PS: in your branch the webpack config isn't published
